Document: gleipnir
Title: Debian gleipnir Manual
Author: <insert document author here>
Abstract: This manual describes what gleipnir is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gleipnir/gleipnir.sgml.gz

Format: postscript
Files: /usr/share/doc/gleipnir/gleipnir.ps.gz

Format: text
Files: /usr/share/doc/gleipnir/gleipnir.text.gz

Format: HTML
Index: /usr/share/doc/gleipnir/html/index.html
Files: /usr/share/doc/gleipnir/html/*.html
